Added User Feature
kiranparajuli589/Blogger pull request #12
Opened 2021-11-18 11:18 UTC by aaronanish12

## Description
### This pr has the following changes:
- acceptance test for various user feature 
- page object model implementation
- before/after hooks implementation

2021-11-18 11:25 UTC, kiranparajuli589 requested changes

2021-11-18 11:25 UTC, kiranparajuli589 commented on tests/acceptance/features/login.feature
> +      | password | demo             |
fix indentation here

2021-11-18 11:25 UTC, kiranparajuli589 commented on package.json
> +    "utils": "^0.3.1"
not required....remove this

2021-11-18 11:25 UTC, kiranparajuli589 commented on package.json
> +    "start:firefox-docker": "docker run --rm -d --network=host -p 4444:4444 -p 5900:5900 --shm-size='2g' selenium/standalone-firefox:4.1.0-prerelease-20211105",
nice. 👍🏼

2021-11-18 11:25 UTC, kiranparajuli589 commented on cucumber.conf.js
> +
why extra line?

2021-11-18 11:25 UTC, kiranparajuli589 commented on tests/acceptance/stepDefinitions/loginContext.js
> +let userListUrl = "http://localhost:3001/api/users/"
use launch url here

2021-11-18 11:25 UTC, kiranparajuli589 commented on tests/acceptance/stepDefinitions/loginContext.js
> +            .then()
not required if not implementation is to be added
```suggestion
```

2021-11-18 11:25 UTC, kiranparajuli589 commented on tests/acceptance/stepDefinitions/loginContext.js
> +    console.log(userToBeCreated["email"] + " is trying to login.")
? 🤔

2021-11-18 11:25 UTC, kiranparajuli589 commented on tests/acceptance/stepDefinitions/userContext.js
> +
```suggestion
```

2021-11-19 09:49 UTC, swoichha commented on tests/acceptance/features/user.feature
> +# Created by anish at 11/16/21
remove this commented line

2021-11-19 09:49 UTC, SwikritiT commented on tests/acceptance/features/user.feature
> +    When the user navigates to the homepage
```suggestion
    When the user navigates to the homepage using the webUI
```

2021-11-19 09:52 UTC, SwikritiT commented on tests/acceptance/features/user.feature
> +    When the user signup using the following details using webUI:
```suggestion
    When the user signs up using the following details using the webUI:
```

2021-11-19 09:54 UTC, SwikritiT commented on tests/acceptance/features/user.feature
> +    When the user signup using the following details using webUI:
same as above

2021-11-21 10:02 UTC, aaronanish12 commented on tests/acceptance/stepDefinitions/loginContext.js
> +    console.log(userToBeCreated["email"] + " is trying to login.")
async banakolai van va dai ? axios use garera user create garda await nagar nahune vayara Gary ho here

2021-11-21 11:53 UTC, merged